appname               = dbx
version               = @VERSION@
display_name          = DBX 数据库管理
desc                  = 一站式数据库管理工具：支持 MySQL、PostgreSQL、SQLite、Redis、MongoDB、ClickHouse、SQL Server、Oracle、DuckDB、Elasticsearch 等 90+ 种数据库，内建 SQL 编辑器、数据网格、表结构对比与 AI 助手。本包为飞牛 fnOS 原生版，无需 Docker，数据与配置全部保存在本应用目录内。
source                = thirdparty
platform              = @PLATFORM@
maintainer            = DBX
maintainer_url        = https://github.com/t8y2/dbx
distributor           = tfgzs
distributor_url       = https://github.com/tfgzs/FnDepot
os_min_version        = 1.2.0
desktop_uidir         = ui
desktop_applaunchname = dbx.Application
service_port          = 4224
checkport             = true
ctl_stop              = true
disable_authorization_path = false
beta                  = no
changelog             = @CHANGELOG@
